export const notesApiConstants = {
    add: '/add',
    remove: '/remove',
    notes: '/api/notes',
    addNotes: '/api/notes/addNotes',
    getNotesList: '/api/notes/getNotesList',
    updateNotes: '/api/notes/updateNotes',
    changesColorNotes: '/api/notes/changesColorNotes',
    pinUnpinNotes: '/api/notes/pinUnpinNotes',
    archiveNotes: '/api/notes/archiveNotes',
    trashNotes: '/api/notes/trashNotes',
    addUpdateReminderNotes: '/api/notes/addUpdateReminderNotes',
    removeReminderNotes: '/api/notes/removeReminderNotes',
    noteLabels: '/api/noteLabels',
    getNoteLabelList: '/api/noteLabels/getNoteLabelList',
    updateNoteLabel: '/updateNoteLabel',
    deleteNoteLabel: '/deleteNoteLabel',
    addLabelToNotes: '/addLabelToNotes',
    searchUserList: '/api/user/searchUserList',
    AddcollaboratorsNotes: '/AddcollaboratorsNotes',
}